import { TextStyle } from 'react-native'
import { getBundleId } from 'react-native-device-info'

export function getBrandBase(appDetails: AppDetails) {
  const {
    app,
    appNoSpaces,
    brandFonts,
    classTitle,
    classTitlePlural,
    coachTitle,
    coachTitlePlural,
    colorPrimary,
    colorSecondary,
    colorTertiary,
    fonts,
    rewardsLevelName,
  } = appDetails
  const buttonTextColor = 'textWhite'
  return {
    brandFonts,
    fonts,
    fontStyles: {} as { [key: string]: TextStyle },
    ANDROID_APPLICATION_ID: getBundleId(),
    APP_NAME: app,
    APP_NAME_NO_SPACES: appNoSpaces,
    BUTTON_GRADIENT: false,
    BUTTON_LARGE_BORDER_COLOR: null as string | null,
    BUTTON_LARGE_FONT: 'fontPrimaryBold',
    BUTTON_LARGE_RADIUS: 4,
    BUTTON_LARGE_TEXT_SIZE: 19,
    BUTTON_SMALL_BORDER_COLOR: null as string | null,
    BUTTON_SMALL_FONT: 'fontPrimaryBold',
    BUTTON_SMALL_RADIUS: 4,
    BUTTON_TEXT_COLOR: buttonTextColor,
    BUTTON_TEXT_COLOR_ALT: 'textWhite',
    COACH_TITLE: coachTitle,
    COACH_TITLE_LC: coachTitle.toLowerCase() as string,
    COACH_TITLE_PLURAL: coachTitlePlural,
    COACH_TITLE_PLURAL_LC: coachTitlePlural.toLowerCase() as string,
    COLOR_ACCOUNT_INPUT_LABEL: 'textBrandSecondary',
    COLOR_APPT_SCHEDULE_DAY_OF_WEEK_SELECTED: 'brandPrimary',
    COLOR_BUTTON_ALT: 'brandPrimary',
    COLOR_BUTTON_BOOK: 'brandPrimary',
    COLOR_BUTTON_BRING_FRIEND: 'brandPrimary',
    COLOR_BUTTON_BRING_FRIEND_TEXT: 'textWhite',
    COLOR_BUTTON_CALENDAR: 'colorButtonCalendar',
    COLOR_BUTTON_CALENDAR_TEXT: 'textWhite',
    COLOR_BUTTON_CANCEL: 'black',
    COLOR_BUTTON_CANCEL_TEXT: 'textWhite',
    COLOR_BUTTON_WAITLIST: 'lightGray',
    COLOR_CHECKBOX_SELECTED_BACKGROUND: 'brandSecondary',
    COLOR_CHECKBOX_SELECTED_CHECK: 'textWhite',
    COLOR_CHECKBOX_SELECTED_CHECK_ALT: 'brandSecondary',
    COLOR_EYEBROW_TEXT: 'brandPrimary',
    COLOR_FILTER_SLIDER: colorPrimary,
    COLOR_FRIEND_INVITE_TITLE_BARS: 'colorWhite',
    COLOR_HEADER: colorPrimary,
    COLOR_HEADER_TAB: colorSecondary,
    COLOR_HEADER_TAB_TEXT: '#FFFFFF',
    COLOR_HEADER_TAB_TEXT_SELECTED: colorPrimary,
    COLOR_HEADER_TEXT: 'textWhite',
    COLOR_HOME_FLOATING_CARD_BACKGROUND: 'white',
    COLOR_HOME_FLOATING_CARD_TEXT: 'brandPrimary',
    COLOR_HOME_REWARDS_BALANCE: 'brandSecondary',
    COLOR_HOME_REWARDS_BALANCE_TEXT: 'colorWhite',
    COLOR_LOGIN_INPUT_BORDER: 'textPlaceholder',
    COLOR_LOGIN_INPUT_PLACEHOLDER: 'textPlaceholder',
    COLOR_LOGIN_INPUT_TEXT: 'textPlaceholder',
    COLOR_LOGIN_VERIFY_BORDER: 'brandPrimary',
    COLOR_LOGIN_VERIFY_CODE: 'brandSecondary',
    COLOR_MODAL_BANNER_ROW: 'brandSecondary',
    COLOR_MODAL_BANNER_ROW_ALT: 'brandPrimary',
    COLOR_MODAL_BANNER_TEXT: 'textWhite',
    COLOR_MODAL_BANNER_TEXT_ALT: 'textWhite',
    COLOR_OVERRIDES: { dark: {}, normal: {} },
    COLOR_PACKAGE_HIGHLIGHT: '#662E9140',
    COLOR_PRIMARY: colorPrimary,
    COLOR_SCHEDULE_DATE: 'textGray',
    COLOR_SCHEDULE_DATE_SELECTED: 'brandSecondary',
    COLOR_SCHEDULE_DATES_SECTION: 'white',
    COLOR_SCHEDULE_DATES_SECTION_BORDER: 'lightGray',
    COLOR_SCHEDULE_FILTER_BUTTON_ACTIVE: 'brandPrimary',
    COLOR_SCHEDULE_FILTER_TEXT: 'textBlack',
    COLOR_SCHEDULE_FILTER_TEXT_ACTIVE: 'textWhite',
    COLOR_SECONDARY: colorSecondary,
    COLOR_SECONDARY_SCREEN_ACTION_ICON: 'textGray',
    COLOR_SECONDARY_SCREEN_BACKGROUND: 'brandSecondary',
    COLOR_SECONDARY_SCREEN_SEPARATOR: 'textPlaceholder',
    COLOR_SECONDARY_SCREEN_TEXT: 'textWhite',
    COLOR_SECONDARY_SCREEN_TEXT_PLACEHOLDER: 'textPlaceholder',
    COLOR_SECONDARY_SCREEN_TITLE: 'textWhite',
    COLOR_SECTION_TITLE: 'textBlack',
    COLOR_TAB_BAR: 'fadedGray',
    COLOR_TAB_BAR_BOOK_BACKGROUND: 'brandPrimary',
    COLOR_TAB_BAR_BOOK_ICON: 'textWhite',
    COLOR_TAB_BAR_BOOK_TEXT: buttonTextColor,
    COLOR_TAB_BAR_ICON_SELECTED: 'textBlack',
    COLOR_TAB_BAR_TEXT: 'textBlack',
    COLOR_TERTIARY: colorTertiary,
    COLOR_TOAST_TEXT: 'textWhite',
    COLOR_WAITLISTED_CLASS: null as string | null,
    DEFAULT_CLASS_LIST_FUTURE: true,
    DEFAULT_COUNTRY: 'US',
    DEFAULT_CURRENCY: '$',
    DEFAULT_FILTER_END_TIME: 23,
    DEFAULT_FILTER_START_TIME: 3,
    IMAGE_CACHE_DIRECTORY: `${appNoSpaces}-img-cache`,
    IMAGES_FRIEND_INVITE: undefined as number | undefined,
    IMAGES_HEADER_BACKGROUND: undefined as number | undefined,
    IMAGES_HOME_HEADER_BACKGROUND: undefined as number | undefined,
    IMAGES_LOGO_HOME: undefined as number | undefined,
    IMAGES_LOGO_LOGIN: undefined as number | undefined,
    IMAGES_REVIEW_HEADER_BACKGROUND: undefined as number | undefined,
    LINK_BASE_URL: `${appNoSpaces}://`,
    LINKS: {} as { [key: string]: string },
    PUSH_CHANNEL_DESCRIPTION: `${app} Push Notifications`,
    PUSH_CHANNEL_ID: `${appNoSpaces}-notifications`,
    PUSH_CHANNEL_NAME: app,
    REWARDS_LEVEL_ICON: null as string | null,
    SIZE_HEADER_TEXT: 22,
    SIZE_HEADER_TEXT_HOME: 22,
    SIZE_MODAL_TITLE: 16,
    SIZE_SECONDARY_SCREEN_TITLE: 44,
    SIZE_SECTION_TITLE: 24,
    STATUS_BAR_CONTENT: 'light-content',
    STATUS_BAR_SCREENS_OMIT: [] as string[],
    STRING_APPT_PROVIDER_TITLE: 'Provider',
    STRING_APPT_PROVIDER_TITLE_PLURAL: 'Providers',
    STRING_BOOKING_CLASS_FULL: `Get in line.`,
    STRING_BOOKING_DISCLAIMER: null as string | null,
    STRING_BRING_FRIEND_DISCLAIMER: null as string | null,
    STRING_BRING_FRIEND_INTRO: `Use one of your available class credits to bring a friend to class.`,
    STRING_BRING_FRIEND_INTRO_NO_PACKAGES: `Select from the options below to purchase credit(s) to book your friend.`,
    STRING_BRING_FRIEND_SUCCESS: '',
    STRING_BUTTON_CANCEL_WAITLIST: 'Pending',
    STRING_CLASS_LIST_TITLE: 'Bookings',
    STRING_CLASS_TITLE: classTitle,
    STRING_CLASS_TITLE_LC: classTitle.toLowerCase() as string,
    STRING_CLASS_TITLE_PLURAL: classTitlePlural,
    STRING_CLASS_TITLE_PLURAL_LC: classTitlePlural.toLowerCase() as string,
    STRING_CLASS_WAITLIST_DISCLAIMER_TEXT: '',
    STRING_ERROR_BRING_FRIEND: null as string | null, //uses API error message
    STRING_FRIEND_INVITE_DESCRIPTION: `Everyone needs a little\n${app} in their lives.\nShare a trial offer with a friend!`,
    STRING_FRIEND_INVITE_DISCLAIMER: `*Must be a new client and local resident.`,
    STRING_FRIEND_INVITE_TITLE: `SHARE A\nTRIAL`,
    STRING_HOME_BUTTON_BOOK: `Book a ${classTitle}`,
    STRING_HOME_FLOATING_CARD_REWARDS: null as string | null,
    STRING_HOME_WELCOME: 'Welcome back',
    STRING_MARKET_LABEL: 'Market',
    STRING_MODAL_CONFIRMATION_CANCEL: `If it's within the late cancel timeframe, you will lose your class credit.`,
    STRING_MODAL_CONFIRMATION_CANCEL_LATE: `This is a late cancellation and your class credit will be lost.`,
    STRING_NO_UPCOMING_CLASSES_BOOKINGS: `You have no upcoming ${classTitlePlural.toLowerCase()}.`,
    STRING_NO_UPCOMING_CLASSES_HOME: `You have no upcoming ${classTitlePlural.toLowerCase()}.`,
    STRING_PACKAGE_LIST_DISCLAIMER: `This data refreshes multiple times a day. To make any changes to an active contract, please contact your studio directly.`,
    STRING_REWARDS_LEVEL_NAME: rewardsLevelName,
    STRING_REWARDS_LEVEL_NAME_LC: rewardsLevelName.toLowerCase() as string,
    STRING_REWARDS_MEMBERSHIP_LEVELS: 'learn more about the membership levels',
    STRING_SCREEN_TITLE_ACCOUNT: 'Account',
    STRING_SCREEN_TITLE_CLASS_HISTORY_CALENDAR: 'Streak Calendar',
    STRING_SCREEN_TITLE_PRICING: 'Pricing',
    STRING_SCREEN_TITLE_SCHEDULE: 'Schedule',
    STRING_SCREEN_TITLE_WORKSHOPS: 'Workshops',
    STRING_SIGN_UP_AGREEMENT: null as string | null,
    STRING_TAB_BAR_BOOK: 'Book',
    STRING_TAB_BAR_CLASSES: classTitlePlural,
    STRING_VISIT_RATING_TITLE: 'Rate Your Visit',
    STRING_VOD_MODAL_TITLE: 'On Demand',
    STRING_VOD_TAB_TITLE: 'Video',
    TRANSFORM_BUTTON_LARGE_TEXT: 'none',
    TRANSFORM_BUTTON_SMALL_TEXT: 'none',
    TRANSFORM_HEADER_TEXT: 'none',
    TRANSFORM_HOME_WELCOME_TEXT: 'none',
    TRANSFORM_ITEM_TITLE_TEXT: 'none',
    TRANSFORM_MODAL_TITLE_TEXT: 'none',
    TRANSFORM_SCREEN_TITLE_TEXT: 'none',
    TRANSFORM_SECTION_TITLE_TEXT: 'none',
    TRANSFORM_TAB_BAR_TEXT: 'none',
    UI_ACCOUNT_CUSTOMER_ID: false,
    UI_ACCOUNT_SWITCHING: false,
    UI_ACCOUNT_SWITCHING_ICON: 'instructor',
    UI_APPOINTMENT_RESULTS_BUTTON_TYPE: 'button' as 'arrow' | 'button',
    UI_APPOINTMENT_RESULTS_PHOTO: true,
    UI_BADGES: false,
    UI_BOOKING_AVATAR: false,
    UI_CLASS_CHECK_IN: false,
    UI_CLASS_FILTERS_HIDE_COACHES: false,
    UI_CLASS_FILTERS_MARKETS: true,
    UI_CLASS_FILTERS_MARKET_KEY: 'StateLong' as 'ClientID' | 'State' | 'StateLong',
    UI_CLASS_FILTERS_MARKET_LABEL: 'StateLong' as 'MarketName' | 'State' | 'StateLong',
    UI_CLASS_WAITLIST_DISCLAIMER: false,
    UI_CLASS_WAITLIST_NUMBER: true,
    UI_CLIENT_ID_HOME: false,
    UI_COACH_HIDE_PAST: false,
    UI_COACH_HIDE_SCHEDULE: false,
    UI_COACH_HIDE_UPCOMING: false,
    UI_COACH_IS_ROOM: false,
    UI_COACH_LAST_INITIAL_ONLY: true,
    UI_COACH_NICKNAME: false,
    UI_CUSTOM_BOOKING: false,
    UI_EMERGENCY_CONTACT_INFO: false,
    UI_FAMILY_BOOKING: false,
    UI_FITMETRIX_BOOKING: false,
    UI_FITMETRIX_STATS: false,
    UI_FRIENDS: false,
    UI_HIDE_PRICING_LOCATIONS: false,
    UI_HOME_BOOK_APPT: false,
    UI_HOME_FAMILY_SWITCHING: false,
    UI_HOME_HEADER_HEIGHT: 232,
    UI_HOME_HIDE_FLOATING_CARDS: false,
    UI_HOME_HIDE_WELCOME: false,
    UI_HOME_REQUEST_SONG: false,
    UI_HOME_REWARDS_BALANCE: false,
    UI_HOME_STUDIO_CONTACT: false,
    UI_HOME_STUDIO_CONTACT_VERSION: 1,
    UI_HOME_STUDIO_INFO_MODAL: false,
    UI_HOME_WEEK_STREAK: false,
    UI_HOME_WELCOME_CHAR: '\n',
    UI_LOCATION_WITH_MARKET: false,
    UI_PACKAGE_CLASSES: false,
    UI_PACKAGE_OPTIONS_BEFORE: false,
    UI_PICK_SPOT: true,
    UI_PRICING_DISABLE_LOCATIONS_LOGGED_IN: false,
    UI_PROFILE_PHOTO_UPLOAD: false,
    UI_PURCHASE_SIGNING: true,
    UI_REVIEW_TIP: false,
    UI_REWARDS: false,
    UI_SCHEDULE_MUSCLE_FOCUS: false,
    UI_SCHEDULE_RESOURCE_NAME: false,
    UI_SCHEDULE_SCREEN: 'ClassSchedule',
    UI_SIGNUP_HIDE_FIELDS: [] as string[],
    UI_TAB_BOOK_APPT: false,
    UI_TAB_VOD: false,
    UI_UPCOMING_ROOM_NAME: false,
  }
}
